# -*- coding: utf-8 -*-
"""bancosapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZftL7qKlkxNAimQTF4tQpmGrIpw7Xx5n
"""

import streamlit as st
import yfinance as yf
import pandas as pd
from PIL import Image
import requests
from io import BytesIO
import time
import base64


# Dicionário com dados dos bancos
bancos = {
    'BBDC4.SA': {
        'empresa': 'Banco Bradesco',
        'ticket': 'BBDC4',
        'logo_path': 'logos/bradesco.png'
    },
    'BBAS3.SA': {
        'empresa': 'Banco do Brasil',
        'ticket': 'BBAS3',
        'logo_path': 'logos/bb.png'
    },
    'ITUB4.SA': {
        'empresa': 'Itaú Unibanco',
        'ticket': 'ITUB4',
        'logo_path': 'logos/itau.png'
    },
    'SANB11.SA': {
        'empresa': 'Banco Santander',
        'ticket': 'SANB11',
        'logo_path': 'logos/santander.png'
    }
}

def buscar_preco(ticker):
    try:
        stock = yf.Ticker(ticker)
        hist = stock.history(period="1d", interval="1m")
        if not hist.empty:
            return round(hist["Close"].iloc[-1], 2)
    except:
        pass
    return "N/A"

st.set_page_config(page_title="Preços em tempo real - Bancos", layout="wide")
st.title("📊 Preço em Tempo Real das Ações - Bancos B3")

refresh_interval = st.slider("⏱️ Atualizar a cada quantos segundos?", min_value=1, max_value=60, value=1)

# Cabeçalho da tabela
col1, col2, col3, col4 = st.columns([1.5, 3, 2, 2])
with col1: st.markdown("**LOGO**")
with col2: st.markdown("**EMPRESA**")
with col3: st.markdown("**TICKET**")
with col4: st.markdown("**PREÇO DA AÇÃO (R$)**")

# Função para criar HTML centralizado verticalmente para textos das colunas
def centralize_text(text):
    return f"""
    <div style='display:flex; align-items:center; height:100%; justify-content:center;'>
        <span style='font-size:16px;'>{text}</span>
    </div>
    """

while True:
    for ticker, info in bancos.items():
        preco = buscar_preco(ticker)

        col1, col2, col3, col4 = st.columns([1.5,3,2,2])

        # Logo (imagem normal)
        if os.path.isfile(info["logo_path"]):
            st_img = col1.image(info["logo_path"], width=100)
        else:
            col1.write("Logo não disponível")

        # Textos centralizados verticalmente e horizontalmente
        col2.markdown(centralize_text(info["empresa"]), unsafe_allow_html=True)
        col3.markdown(centralize_text(info["ticket"]), unsafe_allow_html=True)
        col4.markdown(centralize_text(f"R$ {preco}"), unsafe_allow_html=True)

    time.sleep(refresh_interval)
