# -*- coding: utf-8 -*-
"""bancosapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZftL7qKlkxNAimQTF4tQpmGrIpw7Xx5n
"""

import os
import streamlit as st
import yfinance as yf
from PIL import Image
import time

st.set_page_config(page_title="Ações dos Bancos - B3", layout="wide")
st.title("📊 Acompanhamento em Tempo Real das Ações dos Bancos na B3")

# Caminho absoluto para a pasta logos
LOGO_PATH = os.path.join(os.path.dirname(__file__), "logos")

# Dados dos bancos
bancos = {
    'BBDC4.SA': {
        'empresa': 'Bradesco',
        'ticket': 'BBDC4',
        'logo_path': os.path.join(LOGO_PATH, 'bradesco.png')
    },
    'BBAS3.SA': {
        'empresa': 'Banco do Brasil',
        'ticket': 'BBAS3',
        'logo_path': os.path.join(LOGO_PATH, 'bb.png')
    },
    'ITUB4.SA': {
        'empresa': 'Itaú Unibanco',
        'ticket': 'ITUB4',
        'logo_path': os.path.join(LOGO_PATH, 'itau.png')
    },
    'SANB11.SA': {
        'empresa': 'Santander',
        'ticket': 'SANB11',
        'logo_path': os.path.join(LOGO_PATH, 'santander.png')
    }
}

# Função para buscar o preço da ação
def buscar_preco(ticker):
    acao = yf.Ticker(ticker)
    dados = acao.history(period="1d", interval="1m")
    if not dados.empty:
        return round(dados['Close'].iloc[-1], 2)
    else:
        return "N/A"

# Cabeçalho da tabela
col1, col2, col3, col4 = st.columns([1.5, 3, 2, 2])
with col1: st.markdown("**LOGO**")
with col2: st.markdown("**EMPRESA**")
with col3: st.markdown("**TICKET**")
with col4: st.markdown("**PREÇO DA AÇÃO (R$)**")

# Linhas da tabela
for ticker, info in bancos.items():
    preco = buscar_preco(ticker)
    col1, col2, col3, col4 = st.columns([1.5, 3, 2, 2])

    try:
        img = Image.open(info["logo_path"])
        with col1:
            st.image(img, width=70)
    except Exception as e:
        with col1:
            st.write("❌ Logo não encontrada")
            st.caption(str(e))

    with col2:
        st.write(info["empresa"])
    with col3:
        st.write(info["ticket"])
    with col4:
        st.write(f"R$ {preco}")

# Atualização automática
st.markdown("---")
st.caption("Atualiza automaticamente a cada 30 segundos.")
time.sleep(30)
st.rerun()
