# -*- coding: utf-8 -*-
"""bancosapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZftL7qKlkxNAimQTF4tQpmGrIpw7Xx5n
"""

import streamlit as st
import yfinance as yf
import pandas as pd
from PIL import Image
import requests
from io import BytesIO
import time

# Dicionário com dados dos bancos
bancos = {
    'BBDC4.SA': {
        'empresa': 'Banco Bradesco',
        'ticket': 'BBDC4',
        'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Bradesco_logo.svg/2560px-Bradesco_logo.svg.png'
    },
    'BBAS3.SA': {
        'empresa': 'Banco do Brasil',
        'ticket': 'BBAS3',
        'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Banco_do_Brasil_logo.svg/2560px-Banco_do_Brasil_logo.svg.png'
    },
    'ITUB4.SA': {
        'empresa': 'Itaú Unibanco',
        'ticket': 'ITUB4',
        'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Itau_logo.svg/2560px-Itau_logo.svg.png'
    },
    'SANB11.SA': {
        'empresa': 'Banco Santander',
        'ticket': 'SANB11',
        'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Logo_Banco_Santander.svg/2560px-Logo_Banco_Santander.svg.png'
    }
}

def get_preco_acao(ticker):
    stock = yf.Ticker(ticker)
    info = stock.history(period="1d", interval="1m")
    if not info.empty:
        return round(info["Close"].iloc[-1], 2)
    return "N/A"

st.set_page_config(page_title="Preços em tempo real - Bancos", layout="wide")
st.title("📊 Preço em Tempo Real das Ações - Bancos B3")

refresh_interval = st.slider("⏱️ Atualizar a cada quantos segundos?", min_value=5, max_value=60, value=10)

# Atualização em tempo real
placeholder = st.empty()

while True:
    with placeholder.container():
        cols = st.columns(len(bancos))
        for i, (ticker, info) in enumerate(bancos.items()):
            with cols[i]:
                # Logo
                try:
                    response = requests.get(info["logo_url"])
                    img = Image.open(BytesIO(response.content))
                    st.image(img, width=100)
                except:
                    st.text("Logo não disponível")

                st.markdown(f"**{info['empresa']}**")
                st.markdown(f"🎫 **{info['ticket']}**")

                preco = get_preco_acao(ticker)
                st.metric(label="Preço da Ação (R$)", value=preco)

    time.sleep(refresh_interval)
