# .streamlit/secrets.toml

OPENAI_API_KEY = "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"
